apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel-9-amaranth-mite-44
  namespace: vm-gitops
spec:
  dataVolumeTemplates:
    - metadata:
        name: rhel-9-amaranth-mite-44-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteOnce # Geändert von ReadWriteMany auf ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: ocs-storagecluster-ceph-rbd # Wird jetzt durch Kustomize überschrieben
          volumeMode: Block
  instancetype:
    name: u1.large
  preference:
    name: rhel.9
  running: true
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: rhel-9-amaranth-mite-44-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: cloud@123
              user: cloud-user
          name: cloudinitdisk
